# Generated by Django 5.0.1 on 2025-02-19 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0003_loginattempt_alter_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_leave_increment',
            field=models.DateField(default=datetime.date(2023, 6, 1)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='casual_leaves_remaining',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('CSE', 'Computer Science'), ('ECE', 'Electronics'), ('MECH', 'Mechanical'), ('CIVIL', 'Civil')], max_length=20),
        ),
    ]
